services:
    codefog_news_categories.listener.change_language:
        class: Codefog\NewsCategoriesBundle\EventListener\ChangeLanguageListener

    codefog_news_categories.listener.insert_tags:
        class: Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"

    codefog_news_categories.listener.template:
        class: Codefog\NewsCategoriesBundle\EventListener\TemplateListener

    # Data container
    codefog_news_categories.listener.data_container.content:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\ContentListener
        arguments:
            - "@database_connection"

    codefog_news_categories.listener.data_container.news_category:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryListener
        arguments:
            - "@database_connection"
            - "@contao.framework"
