services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    codefog_news_categories.listener.ajax:
        class: Codefog\NewsCategoriesBundle\EventListener\AjaxListener

    codefog_news_categories.listener.change_language:
        class: Codefog\NewsCategoriesBundle\EventListener\ChangeLanguageListener
        arguments:
            - "@codefog_news_categories.url_generator"

    codefog_news_categories.listener.insert_tags:
        class: Codefog\NewsCategoriesBundle\EventListener\InsertTagsListener
        arguments:
            - "@codefog_news_categories.url_generator"

    codefog_news_categories.listener.news:
        class: Codefog\NewsCategoriesBundle\EventListener\NewsListener
        arguments:
          - "@request_stack"
          - "@codefog_news_categories.search_builder"

    codefog_news_categories.listener.template:
        class: Codefog\NewsCategoriesBundle\EventListener\TemplateListener
        arguments:
            - "@codefog_news_categories.factory"
            - "@contao.framework"
            - "@codefog_news_categories.url_generator"

    # Data container
    codefog_news_categories.listener.data_container.content:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\ContentListener
        arguments:
            - "@database_connection"

    codefog_news_categories.listener.data_container.news_archive:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsArchiveListener
        arguments:
            - "@codefog_news_categories.permission_checker"

    codefog_news_categories.listener.data_container.news_category:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsCategoryListener
        arguments:
            - "@database_connection"
            - "@codefog_news_categories.permission_checker"

    codefog_news_categories.listener.data_container.news:
        class: Codefog\NewsCategoriesBundle\EventListener\DataContainer\NewsListener
        arguments:
            - "@database_connection"
            - "@codefog_news_categories.permission_checker"
