services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    codefog_news_categories.factory:
        class: Codefog\NewsCategoriesBundle\NewsCategoryFactory

    codefog_news_categories.picker:
        class: Codefog\NewsCategoriesBundle\Picker\NewsCategoriesPickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 132 }

    codefog_news_categories.permission_checker:
        class: Codefog\NewsCategoriesBundle\PermissionChecker
        public: false
        arguments:
            - "@security.token_storage"

    codefog_news_categories.search_builder:
        class: Codefog\NewsCategoriesBundle\SearchBuilder
        arguments:
            - "@codefog_news_categories.url_generator"

    codefog_news_categories.url_generator:
        class: Codefog\NewsCategoriesBundle\UrlGenerator
